# Generated by Django 3.0.4 on 2020-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img1',
            field=models.ImageField(blank=True, upload_to='ArtiqueApp/static/images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(blank=True, upload_to='ArtiqueApp/static/images/'),
        ),
    ]
