# Generated by Django 3.0.4 on 2020-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0002_auto_20200424_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Display_main',
            field=models.BooleanField(default=False),
        ),
    ]
