# Generated by Django 3.0.4 on 2020-04-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0004_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArtiqueApp.Product_Type'),
        ),
    ]
