# Generated by Django 3.0.4 on 2020-04-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtiqueApp', '0005_products_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transact_hdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'Inprogress'), ('Completed', 'Completed')], max_length=500)),
                ('Mobile', models.CharField(blank=True, max_length=500)),
                ('Comments', models.TextField(blank=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Datecompleted', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transact_dtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArtiqueApp.Products')),
                ('Transact_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArtiqueApp.Transact_hdr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
