# Generated by Django 3.0.4 on 2020-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0007_transact_dtl_current_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
