# Generated by Django 3.0.4 on 2020-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0009_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dt',
            field=models.CharField(max_length=500),
        ),
    ]
