# Generated by Django 3.0.4 on 2020-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0010_auto_20200501_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dt',
            field=models.DateField(),
        ),
    ]
