# Generated by Django 3.0.4 on 2020-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0011_auto_20200509_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='emailid',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='msg',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
