# Generated by Django 3.0.4 on 2020-05-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0013_transact_hdr_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
