# Generated by Django 3.0.4 on 2020-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0015_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('emailid', models.CharField(max_length=500)),
                ('send_info', models.BooleanField()),
            ],
        ),
    ]
