# Generated by Django 3.0.4 on 2020-05-24 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0016_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transact_dtl',
            name='Order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 24, 13, 8, 38, 259028)),
        ),
    ]
