# Generated by Django 3.0.4 on 2020-05-24 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0017_transact_dtl_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact_dtl',
            name='Order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
