# Generated by Django 3.0.4 on 2020-05-24 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0018_auto_20200524_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transact_dtl',
            name='Order_date',
        ),
        migrations.AddField(
            model_name='transact_hdr',
            name='Order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
