# Generated by Django 3.0.4 on 2020-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0019_auto_20200524_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact_hdr',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'Inprogress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=500),
        ),
    ]
