# Generated by Django 3.0.4 on 2020-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiqueApp', '0020_auto_20200529_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='mobile',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
